Because doesn't work in windows 8, The maven plugin doesn't use a path of nodejs command for execute.
the "nodeExecutable" variable in maven plugin, it's used only for determine, the implementation of compilation, NodeJsLessCompiler or LessCompiler.

I added a pull request for this

[ERROR] C:\temp\lesscss-maven-plugin\target\it\nodejs\src\main\less\test.less [0:0]: Error compiling LESS source
java.io.IOException: Cannot run program "node": CreateProcess error=2, Le fichier spécifié est introuvable
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1042)
	at org.lesscss.mojo.NodeJsLessCompiler.compile(NodeJsLessCompiler.java:134)
	at org.lesscss.mojo.NodeJsLessCompiler.compile(NodeJsLessCompiler.java:116)
	at org.lesscss.mojo.CompileMojo.execute(CompileMojo.java:130)